CREATE OR REPLACE VIEW ORA01.VIEW1
	(ID, NAME, TEL, ADDRESS) 
AS (
select A.ID , 
	   A.NAME, 
       A.TEL , 
       A.ADDRESS
from TABLE1 A
LEFT JOIN TABLE2 B 
	ON A.ID = B.ID
)
/

COMMENT ON TABLE ORA01.VIEW1 IS 'ビュー1'
/

COMMENT ON COLUMN ORA01.VIEW1.ID IS 'ID'
/

COMMENT ON COLUMN ORA01.VIEW1.NAME IS '名前'
/

COMMENT ON COLUMN ORA01.VIEW1.TEL IS '電話番号'
/

COMMENT ON COLUMN ORA01.VIEW1.ADDRESS IS '住所'
/
